export 'user_entity.dart';
export 'user_repos_entity.dart';
export 'star_entity.dart';
export 'trend_entity.dart';
export 'search_repos_entity.dart';
export 'search_user_entity.dart';
export 'repos_entity.dart';
export 'trees_entity.dart';
export 'branch_entity.dart';